agent: any

stages:
    - name: First
      agent: any
      steps:
        - sh: "./scripts/hello.sh"
    - name: Build
      agent: any
      steps:
        - sh: "./scripts/build.sh"
    - name: Tests
      agent: any
      steps:
        - sh: "./scripts/test.sh"

configuration:
    archiveArtifacts:
        - Jenkinsfile.yaml
        - scripts/hello.sh
