agent: any
environment:
  variables:
    FEATURE_ID: 5d2e755d816d970006e7cd4a
    ENVIRONMENT_ID: 5c702eb6976aef2ff81b56e6
  credentials:
    - credentialId : dummyGitRepo
      variable : LOGIN

stages:
    - name: Build
      agent: any
      steps:
        - echo: "Build ok"
    - name: Push
      agent: any
      steps:
        - echo: "Build ok"
    - name: Test
      agent: any
      steps:
        - echo: "Test ok"
    - name: Deploy
      agent: 
        label: Deploy
        customWorkspace: /tmp
        dockerImage: "gcr.io/sysmap-quarks/quarks/voyager/builders/deploy:1.0.3"
      steps:
        - echo: "deploy"
configuration:
    archiveArtifacts:
        - quarks-ci.yaml