agent: any

stages:
    - name: Build
      agent: any
      steps:
        - echo: "Build ok"
    - name: Push
      agent: any
      steps:
        - echo: "Build ok"
    - name: Test
      agent: any
      steps:
        - echo: "Test ok"
    - name: stage2
      agent:
        docketImage: gcr.io/sysmap-quarks/quarks/voyager/builders/deploy:1.0.3
      steps: 
        - args: deploy
      post:
        success:
          echo: "stage2 was a success"

configuration:
    archiveArtifacts:
        - quarks-ci.yaml