agent: any

stages:
    - name: Build
      agent: any
      steps:
        - echo: "Build ok"
    - name: Push
      agent: any
      steps:
        - echo: "Build ok"
    - name: Test
      agent: any
      steps:
        - echo: "Test ok"
    - name: Deploy
      agent:
        dockerImage: maven:3-alpine
      steps: 
        - echo: "Hello from stage2"
configuration:
    archiveArtifacts:
        - quarks-ci.yaml